export {
  getTrending,
  getPopularMovies,
  getUpcomingMovies,
  getPopularTv,
  getMovieDetails,
  getTvDetails,
  discoverMovies,
  discoverTv,
  getMovieRecommendations,
  getTvRecommendations,
  getMovieCredits,
  getTvCredits,
  searchMulti,
  searchMovies,
  searchTv,
} from "./endpoints";
